"""
This file contains code to create pandas dataframe agent
"""

from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
from langchain.llms import OpenAI
import pandas as pd

from typing import List

def create_agent(dataframes_list : List[pd.DataFrame], API_KEY : str, hallucination : float = 0.0) -> create_pandas_dataframe_agent:
    """
    Creates a dataframe agent and returns it.
    params:
        dataframes_list : list of dataframe objects
        API_KEY : str . OpenAPI api key
        hallucination : float value between 0 to 1. 0 for none. ChatGPT defaults with 0.7
    returns:
        A pandas dataframe agent instance.
    """
    agent = create_pandas_dataframe_agent(OpenAI(temperature=hallucination, openai_api_key=API_KEY), dataframes_list, verbose=False)
    return agent


def ask_agent(agent, query) -> str:
    """
    Returns an answer generated by pandas dataframe agent against the query passed in the params.
    params:
        agent : A pandas dataframe agent
        query : str . Question posed to the agent to generate answer.
    returns:
        Dictionary : status value success or failure, response value contains response string. 
    """
    try:
        response = agent.run(query)
        return response
    except (Exception) as e:
        resp = """There was some issue in generating the information asked for.
                Please rephrase your query. If the query is very long make it short."""
        return resp

